### PR TITLE
Additional fields in jobInfoPtr and submitPtr

### PR DESCRIPTION
**Pull request by antst**
1) I added support  jobInfoPtr->runTime, submitPtr->runtimeEstimation and submitPtr->sla
2) added couple of missing new-lines.

It is tested on RHEL6 with LSF 9.1.1.1

### CODE REVIEW

**Comment by adamsla** [comment]
Hi, can you please sign off on the pull request.  Simply read the modified DCO and update the pull request comments with the Signed-off-by line.  Thanks!

**Comment by antst** [comment]
Signed-off-by

**Comment by antst** [comment]
Signed-off-by: Anton Starikov <ant.starikov@gmail.com>

**Comment by adamsla** [comment]
Anton,

Thank you very much.

Larry

**Comment by liuboxa** [comment]
The code is merged.

**Pull request closed without merging**
